[build-system]
requires = ["setuptools>=42", "wheel", "pybind11", "numpy", "cmake"]
build-backend = "setuptools.build_meta"

[project]
name = "MMVII"
dynamic = ["version", "authors", "requires-python", "description"]
dependencies = [
  "numpy"
]

[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux_2_34"
before-build = [
  "pip install pybind11[global]"
]
environment-pass = [ "http_proxy", "https_proxy" ]
repair-wheel-command = "auditwheel repair --disable-isa-ext-check -w {dest_dir} {wheel}"
build = "cp{312,313,314,314t}-manylinux_x86_64"
test-command = ["python {project}/examples/smoke_test.py"]

[tool.cibuildwheel.linux]
before-all = ["./scripts/install_manylinux.sh"]
environment = { CC="clang", CXX="clang++", LD_LIBRARY_PATH="$LD_LIBRARY_PATH:{project}/src/MMVII/bin" }
